(define (problem task)
	(:domain reaching-grid)
	(:objects claw - gripper loc0 loc1 loc2 loc3 loc4 loc5 loc6 loc7 goal - location)
	(:init
		(is_goal goal)
		(at claw loc0)
		(neighbors loc0 loc1)
		(neighbors loc0 loc4)
		(neighbors loc1 loc0)
		(neighbors loc1 loc2)
		(neighbors loc1 loc5)
		(neighbors loc2 loc1)
		(neighbors loc2 loc3)
		(neighbors loc2 loc6)
		(neighbors loc3 loc2)
		(neighbors loc3 loc7)
		(neighbors loc4 loc0)
		(neighbors loc4 loc5)
		(neighbors loc5 loc1)
		(neighbors loc5 loc4)
		(neighbors loc5 loc6)
		(neighbors loc6 loc2)
		(neighbors loc6 loc5)
		(neighbors loc6 loc7)
		(neighbors loc7 loc3)
		(neighbors loc7 loc6)
        (neighbors loc7 goal)
        (neighbors goal loc7)
	)
	(:goal (and 
		(at claw goal))
	)
)
