(define (problem task)
	(:domain reaching-grid)
	(:objects claw - gripper loc0 loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 loc11 loc12 loc13 loc14 loc15 goal - location)
	(:init
		(is_goal goal)
		(at claw loc4)
		(neighbors loc0 loc1)
		(neighbors loc0 loc4)
		(neighbors loc1 loc0)
		(neighbors loc1 loc2)
		(neighbors loc1 loc5)
		(neighbors loc2 loc1)
		(neighbors loc2 loc6)
		(neighbors loc4 loc0)
		(neighbors loc4 loc5)
		(neighbors loc4 loc8)
		(neighbors loc5 loc1)
		(neighbors loc5 loc4)
		(neighbors loc5 loc6)
		(neighbors loc5 loc9)
		(neighbors loc6 loc2)
		(neighbors loc6 loc5)
		(neighbors loc6 loc10)
		(neighbors loc8 loc4)
		(neighbors loc8 loc9)
		(neighbors loc8 loc12)
		(neighbors loc9 loc5)
		(neighbors loc9 loc8)
		(neighbors loc9 loc10)
		(neighbors loc9 loc13)
		(neighbors loc10 loc6)
		(neighbors loc10 loc9)
		(neighbors loc10 loc14)
		(neighbors loc12 loc8)
		(neighbors loc12 loc13)
		(neighbors loc13 loc9)
		(neighbors loc13 loc12)
		(neighbors loc13 loc14)
		(neighbors loc14 loc10)
		(neighbors loc14 loc13)
		(neighbors goal loc7)
		(neighbors loc7 goal)
		
	)
	(:goal (and 
		(at claw goal))
	)
)